site_name: cloudflared-remotefalcon docs
site_url: https://ne0n09.github.io/cloudflared-remotefalcon/docs/
repo_url: https://github.com/Ne0n09/cloudflared-remotefalcon
docs_dir: docs
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
#    code: Red Hat Mono
  icon:
    logo: material/github
  features:
    - navigation.top
    - navigation.instant
    - navigation.expand
    - navigation.path
    - navigation.tracking
    - navigation.indexes
#    - navigation.sections
#    - navigation.instant.preview
#    - navigation.tabs
#    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
#    - content.action.edit
    - content.code.copy
    - header.autohide
    - announce.dismiss
    - toc.integrate

  palette: 
  # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: indigo
      accent: red
  # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: blue
      accent: deep orange  

nav:
  - 'About': 
    - 'About': index.md
    - 'Containers': about/containers.md
    - 'Scripts': about/scripts.md
    - 'Files': about/files.md
    - 'Workflows': about/workflows.md
  - 'Release Notes': release-notes.md
  - 'Installation': 
    - 'Installation': install/index.md
    - 'Prerequisites': install/prerequisites.md
    - 'Cloudflare': install/cloudflare.md
    - 'GitHub': install/github.md
    - 'Remote Falcon': install/remotefalcon.md
  - 'Post-Install': post-install.md
  - 'Updates': updates.md
  - 'Extra': extra.md
  - 'Troubleshooting': troubleshooting.md


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
  - def_list
  - sane_lists

plugins:
  - glightbox
  - search
  - git-revision-date-localized

extra:
  social:
    - icon: simple/github
      link: https://github.com/Ne0n09/cloudflared-remotefalcon

copyright: Copyright &copy; 2025